# 1. Thông tin kết nối MS SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DA3;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234567
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Cấu hình Hibernate (Để Java hiểu cấu trúc bảng SQL)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true